name: CD

on:
  push:
    tags:
      - '**'

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build the Docker image
        run: bash docker_build.sh

      - name: Push the Docker image to docker Hub
        env:
          DOCKER_IMAGE_PREFIX: ${{ secrets.DOCKER_HUB_LOGIN }}
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin && \
          bash docker_publish.sh

# Disabled because of the following unresolved issue while pushing image on github packages:
# Error parsing reference: "docker.pkg.github.com/***/docker-terraform-aws/terraform-aws:0.12.19" is not a valid repository/tag: invalid reference format: repository name must be lowercase
#
#      - name: Push the Docker image to Github packages
#        env:
#          DOCKER_IMAGE_PREFIX: "docker.pkg.github.com/${{ github.repository }}"
#        run: |
#          docker logout && \
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.GITHUB_LOGIN }} --password-stdin && \
#          bash github_packages_publish.sh
